# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\Base_LabRAD_Status.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabRAD_Status_Widget(object):
    def setupUi(self, LabRAD_Status_Widget):
        LabRAD_Status_Widget.setObjectName("LabRAD_Status_Widget")
        LabRAD_Status_Widget.resize(450, 300)
        self.listWidget = QtWidgets.QListWidget(LabRAD_Status_Widget)
        self.listWidget.setGeometry(QtCore.QRect(5, 5, 350, 295))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(LabRAD_Status_Widget)
        QtCore.QMetaObject.connectSlotsByName(LabRAD_Status_Widget)

    def retranslateUi(self, LabRAD_Status_Widget):
        _translate = QtCore.QCoreApplication.translate
        LabRAD_Status_Widget.setWindowTitle(_translate("LabRAD_Status_Widget", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabRAD_Status_Widget = QtWidgets.QWidget()
    ui = Ui_LabRAD_Status_Widget()
    ui.setupUi(LabRAD_Status_Widget)
    LabRAD_Status_Widget.show()
    sys.exit(app.exec_())
