# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\Base_Process_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1058, 826)
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.instructionsFrame = QtWidgets.QFrame(self.centralWidget)
        self.instructionsFrame.setGeometry(QtCore.QRect(0, 0, 1041, 351))
        self.instructionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instructionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.instructionsFrame.setObjectName("instructionsFrame")
        self.stepStaticLabel = QtWidgets.QLabel(self.instructionsFrame)
        self.stepStaticLabel.setGeometry(QtCore.QRect(670, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stepStaticLabel.setFont(font)
        self.stepStaticLabel.setObjectName("stepStaticLabel")
        self.stepLabel = QtWidgets.QLabel(self.instructionsFrame)
        self.stepLabel.setGeometry(QtCore.QRect(740, 0, 28, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stepLabel.setFont(font)
        self.stepLabel.setObjectName("stepLabel")
        self.insDisplay = QtWidgets.QTextEdit(self.instructionsFrame)
        self.insDisplay.setGeometry(QtCore.QRect(3, 3, 661, 351))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.insDisplay.setFont(font)
        self.insDisplay.setAcceptDrops(False)
        self.insDisplay.setReadOnly(True)
        self.insDisplay.setObjectName("insDisplay")
        self.statusStaticLabel = QtWidgets.QLabel(self.instructionsFrame)
        self.statusStaticLabel.setGeometry(QtCore.QRect(820, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusStaticLabel.setFont(font)
        self.statusStaticLabel.setObjectName("statusStaticLabel")
        self.statusLabel = QtWidgets.QLabel(self.instructionsFrame)
        self.statusLabel.setEnabled(True)
        self.statusLabel.setGeometry(QtCore.QRect(883, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.instructionsFrame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(670, 40, 271, 311))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.coreParamsLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.coreParamsLayout.setContentsMargins(0, 0, 0, 0)
        self.coreParamsLayout.setHorizontalSpacing(7)
        self.coreParamsLayout.setVerticalSpacing(5)
        self.coreParamsLayout.setObjectName("coreParamsLayout")
        self.parametersFrame = QtWidgets.QFrame(self.centralWidget)
        self.parametersFrame.setGeometry(QtCore.QRect(-1, 399, 1041, 231))
        self.parametersFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parametersFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parametersFrame.setObjectName("parametersFrame")
        self.proceedButton = QtWidgets.QPushButton(self.centralWidget)
        self.proceedButton.setEnabled(True)
        self.proceedButton.setGeometry(QtCore.QRect(164, 355, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.proceedButton.setFont(font)
        self.proceedButton.setObjectName("proceedButton")
        self.abortButton = QtWidgets.QPushButton(self.centralWidget)
        self.abortButton.setGeometry(QtCore.QRect(600, 355, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.abortButton.setFont(font)
        self.abortButton.setObjectName("abortButton")
        self.recipeFrame = QtWidgets.QFrame(self.centralWidget)
        self.recipeFrame.setGeometry(QtCore.QRect(-1, 629, 1041, 131))
        self.recipeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recipeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recipeFrame.setObjectName("recipeFrame")
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menuBar.setObjectName("menuBar")
        mainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.stepStaticLabel.setText(_translate("mainWindow", "Step #:"))
        self.stepLabel.setText(_translate("mainWindow", "##"))
        self.statusStaticLabel.setText(_translate("mainWindow", "Status:"))
        self.statusLabel.setText(_translate("mainWindow", "<Standby>"))
        self.proceedButton.setText(_translate("mainWindow", "Start"))
        self.abortButton.setText(_translate("mainWindow", "Abort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
