# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\Recipe_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecipeDialog(object):
    def setupUi(self, RecipeDialog):
        RecipeDialog.setObjectName("RecipeDialog")
        RecipeDialog.resize(270, 381)
        self.recipeListWidget = QtWidgets.QListWidget(RecipeDialog)
        self.recipeListWidget.setGeometry(QtCore.QRect(10, 5, 250, 301))
        self.recipeListWidget.setObjectName("recipeListWidget")
        self.loadPrevCheckBox = QtWidgets.QCheckBox(RecipeDialog)
        self.loadPrevCheckBox.setGeometry(QtCore.QRect(30, 310, 210, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadPrevCheckBox.setFont(font)
        self.loadPrevCheckBox.setChecked(True)
        self.loadPrevCheckBox.setObjectName("loadPrevCheckBox")
        self.loadButton = QtWidgets.QPushButton(RecipeDialog)
        self.loadButton.setGeometry(QtCore.QRect(30, 350, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.cancelButton = QtWidgets.QPushButton(RecipeDialog)
        self.cancelButton.setGeometry(QtCore.QRect(140, 350, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(RecipeDialog)
        QtCore.QMetaObject.connectSlotsByName(RecipeDialog)

    def retranslateUi(self, RecipeDialog):
        _translate = QtCore.QCoreApplication.translate
        RecipeDialog.setWindowTitle(_translate("RecipeDialog", "Dialog"))
        self.loadPrevCheckBox.setText(_translate("RecipeDialog", "Load Previous Parameters"))
        self.loadButton.setText(_translate("RecipeDialog", "Load"))
        self.cancelButton.setText(_translate("RecipeDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecipeDialog = QtWidgets.QDialog()
    ui = Ui_RecipeDialog()
    ui.setupUi(RecipeDialog)
    RecipeDialog.show()
    sys.exit(app.exec_())
