# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\Base_Tip_Selection_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipSelectionDialog(object):
    def setupUi(self, TipSelectionDialog):
        TipSelectionDialog.setObjectName("TipSelectionDialog")
        TipSelectionDialog.resize(270, 429)
        self.loadButton = QtWidgets.QPushButton(TipSelectionDialog)
        self.loadButton.setGeometry(QtCore.QRect(30, 395, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.cancelButton = QtWidgets.QPushButton(TipSelectionDialog)
        self.cancelButton.setGeometry(QtCore.QRect(140, 395, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.treeWidget = QtWidgets.QTreeWidget(TipSelectionDialog)
        self.treeWidget.setGeometry(QtCore.QRect(10, 5, 250, 375))
        self.treeWidget.setObjectName("treeWidget")

        self.retranslateUi(TipSelectionDialog)
        QtCore.QMetaObject.connectSlotsByName(TipSelectionDialog)

    def retranslateUi(self, TipSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        TipSelectionDialog.setWindowTitle(_translate("TipSelectionDialog", "Dialog"))
        self.loadButton.setText(_translate("TipSelectionDialog", "Load"))
        self.cancelButton.setText(_translate("TipSelectionDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TipSelectionDialog = QtWidgets.QDialog()
    ui = Ui_TipSelectionDialog()
    ui.setupUi(TipSelectionDialog)
    TipSelectionDialog.show()
    sys.exit(app.exec_())
