# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\Base_Status_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusWindow(object):
    def setupUi(self, StatusWindow):
        StatusWindow.setObjectName("StatusWindow")
        StatusWindow.resize(1470, 810)
        self.plotFrame = QtWidgets.QFrame(StatusWindow)
        self.plotFrame.setGeometry(QtCore.QRect(915, 5, 550, 800))
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.variablesFrame = QtWidgets.QFrame(StatusWindow)
        self.variablesFrame.setGeometry(QtCore.QRect(510, 5, 400, 800))
        self.variablesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.variablesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.variablesFrame.setObjectName("variablesFrame")
        self.ManualWidgetFrame = QtWidgets.QFrame(StatusWindow)
        self.ManualWidgetFrame.setGeometry(QtCore.QRect(5, 30, 500, 750))
        self.ManualWidgetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ManualWidgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ManualWidgetFrame.setObjectName("ManualWidgetFrame")

        self.retranslateUi(StatusWindow)
        QtCore.QMetaObject.connectSlotsByName(StatusWindow)

    def retranslateUi(self, StatusWindow):
        _translate = QtCore.QCoreApplication.translate
        StatusWindow.setWindowTitle(_translate("StatusWindow", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StatusWindow = QtWidgets.QWidget()
    ui = Ui_StatusWindow()
    ui.setupUi(StatusWindow)
    StatusWindow.show()
    sys.exit(app.exec_())
