# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\Base_Status_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusWindow(object):
    def setupUi(self, StatusWindow):
        StatusWindow.setObjectName("StatusWindow")
        StatusWindow.resize(1015, 808)
        self.vacuumFrame = QtWidgets.QFrame(StatusWindow)
        self.vacuumFrame.setGeometry(QtCore.QRect(5, 5, 450, 300))
        self.vacuumFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vacuumFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vacuumFrame.setObjectName("vacuumFrame")
        self.plotFrame = QtWidgets.QFrame(StatusWindow)
        self.plotFrame.setGeometry(QtCore.QRect(460, 5, 905, 831))
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.plot1 = PlotWidget(self.plotFrame)
        self.plot1.setGeometry(QtCore.QRect(0, 0, 550, 400))
        self.plot1.setObjectName("plot1")
        self.plot2 = PlotWidget(self.plotFrame)
        self.plot2.setGeometry(QtCore.QRect(0, 400, 550, 400))
        self.plot2.setObjectName("plot2")
        self.variablesFrame = QtWidgets.QFrame(StatusWindow)
        self.variablesFrame.setGeometry(QtCore.QRect(5, 310, 450, 490))
        self.variablesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.variablesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.variablesFrame.setObjectName("variablesFrame")

        self.retranslateUi(StatusWindow)
        QtCore.QMetaObject.connectSlotsByName(StatusWindow)

    def retranslateUi(self, StatusWindow):
        _translate = QtCore.QCoreApplication.translate
        StatusWindow.setWindowTitle(_translate("StatusWindow", "Form"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StatusWindow = QtWidgets.QWidget()
    ui = Ui_StatusWindow()
    ui.setupUi(StatusWindow)
    StatusWindow.show()
    sys.exit(app.exec_())
